const mongoose = require("mongoose");
const { Schema } = mongoose;

//schema attributes. id is 2nd listed on mongo; _id is autogenerated by mongo

const productSchema = new Schema({
  id: String,
  productName: {
    type: String,
    required: true,
  },
  brand: {
    type: String,
    required: true,
  },
  image: {
    type: String,
    required: true,
  },
  price: {
    type: String,
    required: true,
  },
});

const Product = mongoose.model("Product", productSchema, "products");

//export
module.exports = Product;
